version: "3.7"

services:
  vrising:
    container_name: v-rising
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./saves
        target: /saves
    environment:
      # base server settings
      - VR_NAME="maymay town"
      - VR_PASSWORD="${VR_PASSWORD}"
      - VR_DESCRIPTION="be nice"
      - VR_SAVE_NAME=maymay1
      - VR_DIFFICULTY_PRESET=Difficulty_Normal
      - VR_ADDRESS=0.0.0.0
      - VR_SAVE_COUNT=100
      - VR_RESET_DAYS_INTERVAL=0
      - VR_GAME_PORT=27015
      - VR_QUERY_PORT=27016
      - VR_RCON_PORT=25575
      - VR_MAX_ADMINS=4
      - VR_MAX_USERS=40
      - VR_HIDEIPADDRESS=true
      - VR_LOWER_FPS_WHEN_EMPTY=true
      - VR_LOWER_FPS_WHEN_EMPTY_VALUE=5
      - VR_RCON_PASSWORD=${VR_RCON_PASSWORD}
      - VR_LIST_ON_STEAM=true
      - VR_LIST_ON_EOS=true
      - VR_SECURE=true
      # game tweaks
      - VR_RESOURCE_YIELD_MOD=2.0
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
