version: "3.7"

services:
  vrising:
    container_name: v-rising
    build: .
    restart: unless-stopped
    volumes:
      - type: bind
        source: ./saves
        target: /saves
    environment:
      # base server settings
      - VR_NAME=maymay town - 2.5x resource yield, slow decay
      - VR_PASSWORD=${VR_PASSWORD}
      - VR_DESCRIPTION=be nice
      - VR_SAVE_NAME=maymay1
      - VR_DIFFICULTY_PRESET=Difficulty_Normal
      - VR_ADDRESS=${VR_ADDRESS}
      - VR_SAVE_COUNT=100
      - VR_RESET_DAYS_INTERVAL=0
      - VR_GAME_PORT=27020
      - VR_QUERY_PORT=27021
      - VR_RCON_PORT=27022
      - VR_API_PORT=27023
      - VR_MAX_ADMINS=4
      - VR_MAX_USERS=40
      - VR_HIDEIPADDRESS=true
      - VR_LOWER_FPS_WHEN_EMPTY=true
      - VR_LOWER_FPS_WHEN_EMPTY_VALUE=5
      - VR_RCON_PASSWORD=${VR_RCON_PASSWORD}
      - VR_LIST_ON_STEAM=false
      - VR_LIST_ON_EOS=true
      - VR_SECURE=true
      # game tweaks
      - VR_RESOURCE_YIELD_MOD=2.5
      - VR_ESSENCE_DRAIN_MOD=0.2
      - VR_ESSENCE_YIELD_MOD=2.5
      # admins
      - VR_ADMIN_STEEAMID_1=${VR_ADMIN_STEEAMID_1}
      - VR_ADMIN_STEEAMID_2=${VR_ADMIN_STEEAMID_2}
      - VR_ADMIN_STEEAMID_3=${VR_ADMIN_STEEAMID_3}
    ports:
      - 9876:9876/udp
      - 9877:9877/udp
      # - 27015:27015/tcp
      # - 27015:27015/udp
      # - 27015:27016/tcp
      # - 27015:27016/udp
